### PR TITLE
Cache unique hash (MerkleTree)

### PR DESCRIPTION
**Pull request by shargon**

### CODE REVIEW

**Comment by yongjiema** [comment]
Will it cause a task has the same `MerkleTree` but different sequence is dropped?

**Comment by shargon** [comment]
If the hashes are equal, the merkletree will be equal, but we don't need to process them  multiple times, just one

**Comment by yongjiema** [comment]
> If the hashes are equal, the merkletree will be equal, but we don't need to process them multiple times, just one

But I think the merkletree may be same even if the hashes are not equal.

**Comment by shargon** [comment]
it can't, is a hash of hashes

**Comment by yongjiema** [comment]
> it can't, is a hash of hashes

I don't think so, can you double check from https://en.wikipedia.org/wiki/Collision_attack?

**Comment by shargon** [comment]
The same probability that exists in the block, but the difference is that here, is not something crucial

**Comment by yongjiema** [comment]
I am not sure it is a improvement here, but we can consider the suggestion https://github.com/neo-project/neo/pull/900#discussion_r308095618 from @erikzhang, but must be aware of the consensus tasks.

**Comment by igormcoelho** [comment]
The only collision attack I know on MerkleTree is related to incomplete leafs (this have been done on Bitcoin already). There's a simple solution to that, as far as I remember.

**Comment by shargon** [comment]
I will close it, optimizations could come later

**Pull request closed without merging**
